name: Installation, test and coverage
on: [push]

jobs:
  test:
    # Multiple platforms have been disabled because Windows and OSx needs more credits than what we have.
    # Don't use them during class or the assignment
    name: py${{ matrix.python-version }} # ${{ matrix.platform }}
    runs-on: ubuntu-latest # ${{ matrix.platform }}
    strategy:
      matrix:
        # platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.11]

    steps:
      # Checkout the repository and setups the machine to use python
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install testing dependencies
        run: |
          pip install pytest pytest-cov
      - name: Install package
        run: |
          pip install .
      - name: Run tests
        run: pytest --cov=./